# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app_manager.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pp_manager.proto\x12\nappmanager\"E\n\x10\x44\x65ployAppRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x03 \x01(\t\"5\n\x11\x44\x65ployAppResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"+\n\x17MonitoringStatusRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\";\n\x18MonitoringStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\";\n\x17\x43onfigureServiceRequest\x12\x10\n\x08\x61pp_name\x18\x01 \x01(\t\x12\x0e\n\x06\x63onfig\x18\x02 \x01(\t\"<\n\x18\x43onfigureServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x02\n\nAppManager\x12H\n\tDeployApp\x12\x1c.appmanager.DeployAppRequest\x1a\x1d.appmanager.DeployAppResponse\x12]\n\x10MonitoringStatus\x12#.appmanager.MonitoringStatusRequest\x1a$.appmanager.MonitoringStatusResponse\x12]\n\x10\x43onfigureService\x12#.appmanager.ConfigureServiceRequest\x1a$.appmanager.ConfigureServiceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPLOYAPPREQUEST']._serialized_start=33
  _globals['_DEPLOYAPPREQUEST']._serialized_end=102
  _globals['_DEPLOYAPPRESPONSE']._serialized_start=104
  _globals['_DEPLOYAPPRESPONSE']._serialized_end=157
  _globals['_MONITORINGSTATUSREQUEST']._serialized_start=159
  _globals['_MONITORINGSTATUSREQUEST']._serialized_end=202
  _globals['_MONITORINGSTATUSRESPONSE']._serialized_start=204
  _globals['_MONITORINGSTATUSRESPONSE']._serialized_end=263
  _globals['_CONFIGURESERVICEREQUEST']._serialized_start=265
  _globals['_CONFIGURESERVICEREQUEST']._serialized_end=324
  _globals['_CONFIGURESERVICERESPONSE']._serialized_start=326
  _globals['_CONFIGURESERVICERESPONSE']._serialized_end=386
  _globals['_APPMANAGER']._serialized_start=389
  _globals['_APPMANAGER']._serialized_end=665
# @@protoc_insertion_point(module_scope)
