# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app_manager_pb2 as app__manager__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeployApp = channel.unary_unary(
                '/appmanager.AppManager/DeployApp',
                request_serializer=app__manager__pb2.DeployAppRequest.SerializeToString,
                response_deserializer=app__manager__pb2.DeployAppResponse.FromString,
                _registered_method=True)
        self.MonitoringStatus = channel.unary_unary(
                '/appmanager.AppManager/MonitoringStatus',
                request_serializer=app__manager__pb2.MonitoringStatusRequest.SerializeToString,
                response_deserializer=app__manager__pb2.MonitoringStatusResponse.FromString,
                _registered_method=True)
        self.ConfigureService = channel.unary_unary(
                '/appmanager.AppManager/ConfigureService',
                request_serializer=app__manager__pb2.ConfigureServiceRequest.SerializeToString,
                response_deserializer=app__manager__pb2.ConfigureServiceResponse.FromString,
                _registered_method=True)


class AppManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeployApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitoringStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeployApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployApp,
                    request_deserializer=app__manager__pb2.DeployAppRequest.FromString,
                    response_serializer=app__manager__pb2.DeployAppResponse.SerializeToString,
            ),
            'MonitoringStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitoringStatus,
                    request_deserializer=app__manager__pb2.MonitoringStatusRequest.FromString,
                    response_serializer=app__manager__pb2.MonitoringStatusResponse.SerializeToString,
            ),
            'ConfigureService': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureService,
                    request_deserializer=app__manager__pb2.ConfigureServiceRequest.FromString,
                    response_serializer=app__manager__pb2.ConfigureServiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appmanager.AppManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appmanager.AppManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeployApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/DeployApp',
            app__manager__pb2.DeployAppRequest.SerializeToString,
            app__manager__pb2.DeployAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitoringStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/MonitoringStatus',
            app__manager__pb2.MonitoringStatusRequest.SerializeToString,
            app__manager__pb2.MonitoringStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/ConfigureService',
            app__manager__pb2.ConfigureServiceRequest.SerializeToString,
            app__manager__pb2.ConfigureServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
